spartan: Patch libAlgoProcess to resolve duplicate dependencies
Fixes:
error: module "libAlgoProcess" variant
"android_vendor_arm64_armv9-a_static": depends on multiple
versions of the same aidl_interface:
android.hardware.graphics.common-V3-ndk-source,
android.hardware.graphics.common-V5-ndk-source

Change-Id: If0be3da5c13e45c6c59dde98bb80f35eb22bf846